name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        # Install sqlite3 for build process if needed
        npm install better-sqlite3 --no-save
      
    - name: Convert images to WebP
      run: npm run convert-images
      
    - name: Build static site
      run: npm run build:static
      
    - name: Fix GitHub Pages paths
      run: |
        # Update HTML base path and asset paths for GitHub Pages
        sed -i 's|<base href="/">|<base href="/Repo1/">|g' dist/index.html
        sed -i 's|href="/assets/|href="/Repo1/assets/|g' dist/index.html
        sed -i 's|src="/assets/|src="/Repo1/assets/|g' dist/index.html
        sed -i 's|/webp-images/|/Repo1/webp-images/|g' dist/index.html
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true